algoritmo "VOLUME"
// Função :Medir o Volume da Caixa
// Autor :Rafael e Daniel
// Data : 22/08/2013
// Seção de Declarações 
var
BASE,LADO,ALTURA:REAL
VOLUME:REAL
inicio
// Seção de Comandos
ESCREVA("DIGITE O VALOR DA BASE")
LEIA(BASE)
ESCREVA("DIGITE O VALOR DE LADO")
LEIA(LADO)
ESCREVA("DIGITE O VALOR DA ALTURA")
LEIA(ALTURA)
VOLUME:=(BASE*LADO*ALTURA)

ESCREVA("O VOLUME DA CAIXA É",VOLUME)
fimalgoritmo
