algoritmo "CONVERSOR"
// Função : Converter Cº para Fº
// Autor : Daniel Galhardi TheWorldGodOnlyKnows & Rafael Zulzke TheDarkShinigami
// Data : 28/08/2013
// Seção de Declarações 
var
GrausCelsius:REAL
Fahrenheit:REAL
inicio
// Seção de Comandos
ESCREVAL("QUAL É A TEMPERATURA ATUAL EM Cº?")
Leia(GrausCelsius)
Fahrenheit:=(9*GrausCelsius+160)/5
ESCREVAL("A TEMPERATURA ATUAL É",Fahrenheit,"Fº")
fimalgoritmo
